name: Deploy ASP.NET CORE

on: 
	push:
		branches:
			-main

env:
	AZURE_WEBAPP_NAME: appsvc-orderprocessingapi-dev
	AZURE_WEBAPP_PATH: '.'
	DOTNOT_VERSION: '6'

jobs:
	build-and-deploy:
		runs-on: ubuntu-latest
		steps:
			
			- uses: actions/checkout

			- name: Login via Azure CLI
				uses: azure/login@v1
				with: 
					creds: ${{ secrets.AZURE_CREDENTIALS }}

			- name: SETUP .NET CORE
				uses: actions/setup-dotnet@v1
				with: 
					dotnet-version: ${{ env.DOTNET_VERSION }}

			- name: dotnet build + publish
				run: |
					dotnet build --configuration release
					dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PATH }}

			- name: Deploy to App Service
				uses: azure/webapps-deploy@v2
				with: 
					app-name: ${{ env.AZURE_WEBAPP_NAME }}
					package: '${{ env.AZURE_WEBAPP_PATH }}'
